### ISSUE TITLE
Remove Fees & Deposits section

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#47]
create a proposal for where to put relevant information

**Comment by legion80** [comment]
Over to @zhangshichao0322 to complete the fix.

**Comment by legion80** [comment]
Retitled since we are doing this. Needs ZH translation then we can close.

**Comment by zhangshichao0322** [comment]
Done. We can close.

**Comment by legion80** [comment]
Done in dde6302.

To confirm, there as no need to edit step 3 of the How to Apply section?

**Comment by legion80** [comment]
Additional work in e65849c. Done.
