### ISSUE TITLE
Heading of:  Program details and application (under Piano Program and others) 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#54]
in the top heading on the Apply page (AND in the menu on the right): 
   Program details and application

I think the other words (after Program) should be upper case (except "and") to keep it consistent with the other headings and typically words in a heading ( except conjunctions) are upper case. 

Program Details and Application

Also with Recording guidelines subheading, guidelines should be upper case: 
Guidelines

I'm happy to do it myself but wanted to clear it first.

**Comment by legion80** [comment]
That's fine with me.
