### ISSUE TITLE
2nd concert photo on Home Page (8 piano concert) 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#55]
I don't love this photo here because it is so black & white. The original had some blue in it. Plus the images are so miniscule. 
I don't think it looks very appealing even though it was a spectacular event. 

Your reaction?

**Comment by legion80** [comment]
It's reasonable to replace it with something else, or remove it. Which would you like to do? What do you suggest we use instead?

**Comment by Amalfi-Festival** [comment]
What about the photo of Ian jones performing at San Domenico? Not as dramatic by any means but I'd be curious to see how it looks. What if we put that one on top and the choral photo underneath?

**Comment by Amalfi-Festival** [comment]
Sorry, the Ian Jones photo is in the Piano folder in PHOTOS

**Comment by legion80** [comment]
The subject is good but the digital zoom is very close so it looks quite blurry even though the image is large. I can try; it'll be ok on the webpage, if people click on it on desktop it won't look as good
