### ISSUE TITLE
Redundant heading in ZH "how to apply"?

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#61]
Originally checked in as d04faf.

https://amalfi-festival.github.io/amalfi-festival-org/piano-teaching-zh#how-to-apply

The top header is 网上报名

Right below it is 报名流程

It seems like one of these should be the top header.

**Comment by zhangshichao0322** [comment]
Good catch! Let's use the latter, 报名流程, as the header and delete 网上报名
