### ISSUE TITLE
CONTACT info - Adjust phone numbers 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#64]
We need to remove the Italian phone number under the U.S. one. Only good in the summer and goes to Reginna Hotel! 
(Sorry, I don't know how to find that section)

**Comment by zhangshichao0322** [comment]
Removed.

**Comment by zhangshichao0322** [comment]
We should then add +1 in front of the US phone number.

**Comment by zhangshichao0322** [comment]
Done.
