### ISSUE TITLE
COLD FEET - Leslie (Home page) 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#69]
I am still very unhappy with the text on the home page because that section was formerly on a back page called Festival Overview. It was descriptive and also provided a history of the festival but still contained the original vision of the festival that was much more multi-faceted with the Vocal/Opera program, Chamber Music and a big guest program of different groups. So, the target audience of the home page was very different. 

I still need to seriously adjust and reconfigure the presentation but haven't had the bandwidth to come up with exactly what I want. That is the HOME PAGE after all and I feel it is inadequate. 

Of course I now want to delay the launching but realize that is not the best solution.  Can you tell me If the revised text is in bigger blocks, will that disrupt the lay-out? 

I'm feeling very panicky about pushing "GO"!  I look forward to your reassurances.

**Comment by zhangshichao0322** [comment]
I guess we can always change the texts however we want, without messing up the format. Correct Jon? I still think it would be the best to get the site ready, especially we need to attract pianists to apply. My feeling is that most piano students will just jump right into the piano section without even reading the front page. Not to say that the front page is less important, though. Thoughts?

**Comment by legion80** [comment]
We can always adjust the text after release. @Amalfi-Festival what do you mean by "bigger blocks"?

I can try a treatment that's similar to what the piano page has. Or something maybe even more stark so that they don't look exactly the same.

**Comment by Amalfi-Festival** [comment]
Okay, that's fine. I just meant slightly longer text blocks. 
No problem, just feeling nervous and worried about making things more complicate later on. 

 We can stay on schedule.

**Comment by legion80** [comment]
Does the new home page design address some of your concerns? If so, would you feel comfortable closing this issue?

**Comment by legion80** [comment]
Closing, per discussion offline.
