### ISSUE TITLE
Lay out/ Line up of Programs on Home Page

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#70]
I would like the Choral Tour to be the 2nd listing in the lay out instead of Piano Teaching. While it may seem more logical to have Piano Teaching follow piano, the Choral Tour is definitely happening and also has a longer history as a program. Plus we are still accepting sign ups. 

This also makes sense since very few people will be looking at that section on the website since we are mainly (if not exclusively) marketing this to teachers in China.

**Comment by zhangshichao0322** [comment]
I don't know where to make the adjustment. Jon, thanks!

**Comment by Amalfi-Festival** [comment]
Yes, I just wanted you (Shichao) to be aware and feel free to comment.

**Comment by legion80** [comment]
this will affect the header and footer as well.

**Comment by legion80** [comment]
<img width="392" alt="Screenshot 2024-01-21 at 9 57 28 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/620faada-eaa3-405b-aa05-8e2ee8ea2fad">
<img width="136" alt="Screenshot 2024-01-21 at 9 58 03 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/38dc5647-740a-4a00-a82e-3bc4adf8b236">
<img width="675" alt="Screenshot 2024-01-21 at 9 58 35 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/69efd5e5-4851-4e72-a537-4a2c91cf8489">

Is this ok or did you want it only on the home page?

**Comment by zhangshichao0322** [comment]
Why don't we then do alphabetical? 
Choral - Piano - Piano Teaching - VA - Writing? 
Plus Choral is the one that happens the earliest. 
Leslie?

**Comment by Amalfi-Festival** [comment]
Okay that's a great solution! 
Sorry I didn't see this earlier. 
Thanks!!
