### ISSUE TITLE
Could consider alternative fonts for ZH

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#71]
I don't know how often fonts are used for ZH body or heading text, but I wanted to offer an option in case it made more stylistic sense.

There are at least these fonts on Google Fonts:

https://fonts.google.com/?subset=chinese-simplified&noto.script=Hans

I thought we could potentially use ZCOOL XiaoWei for headers. I did not try it to see how it looked alongside the current font we're using, Fahkwang https://fonts.google.com/specimen/Fahkwang?noto.script=Hans&query=fahkwang

**Comment by zhangshichao0322** [comment]
ZCOOL XiaoWei is definitely not commonly used. I had actually not seen it before. The top two are much more common and formal.  The 1st should be a good header.

**Comment by legion80** [comment]
The only reason I would use something different is for giving a different stylistic feeling. Google's standard Noto fonts seem similar enough to me that what we already have that I wouldn't use those instead.

Closing then.
