### ISSUE TITLE
Double-checking on collage in front brochure page of piano program

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#72]
Are we all set with the collage at the bottom of that page?

**Comment by Amalfi-Festival** [comment]
If Shichao doesn't mind or has time to rearrange the piano one, I do have some recs. He sent me a new one yesterday that I didn't get to commenting on. There are still some wonky photos I'd prefer to swap. 
OR we can wait till after launch. Whatever makes the most sense for you two.

**Comment by legion80** [comment]
Depends on how many. It's relatively fast to swap, especially if I had a list of which picture to place where.

**Comment by legion80** [comment]
Sorry my comment makes no sense in the context of just the collage. I thought you were referring to individual photos elsewhere on the site.

I don't know how hard it is to swap photos that are part of the collage.

**Comment by legion80** [comment]
Swapping the collage itself is easy.

**Comment by legion80** [comment]
New one created in 26b22da.
