### ISSUE TITLE
Add localizations for other programs in the festival

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#80]
In the front matter for visual arts, writers, and choral, add `title-zh`. Example was shown offline.

**Comment by zhangshichao0322** [comment]
I'm sorry, I was lost... Where exactly do I add those? I added this : 
webpage-data:
    menu-title: Choral
    menu-title-zh: 合唱之旅

**Comment by zhangshichao0322** [comment]
Where is the "offline" example? I couldn't seem to find it.

**Comment by legion80** [comment]
It was in the thread.

So at the top of `_programs/choral.md`, for example:

```
---
title: Choral Tour
title-zh: asdf
sessions:
...
```

**Comment by zhangshichao0322** [comment]
I see!! Fixed then.
