### ISSUE TITLE
Travel Insurance Info page - Link needed in Cancellation section for CHORAL 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#85]
The travel insurance info. page (which is currently linked to the relevant section on FAQ page) should also be linked to the mention of travel insurance in the Cancellation & Refunds section for Choral (3rd point). 

My understanding is that I cannot touch this section and I don't want to make a mistake. 

Thanks!

**Comment by legion80** [comment]
I'll also link it for the other programs, since the alternate sentence is "Travel insurance is strongly recommended..."

**Comment by legion80** [comment]
Spun off a new issue for ZH.
