### ISSUE TITLE
Edit on Choral Page - How to Apply , point 3 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#87]
Please modify Point 3 on Choral Page, "How to Apply" section, as follows:

Applications are accepted until spaces are filled. Your participation in the program may not be considered confirmed until deposits are accepted by Center for Musical Studies and you have received a formal confirmation notification

**Comment by legion80** [comment]
I am going to have this affect every program. Let me know if this is an issue.

**Comment by legion80** [comment]
CC @zhangshichao0322 -- if this needs an adjustment on the ZH side.
