### ISSUE TITLE
Add Staff Member to Staff page 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#88]
Please add the following staff member between Jon Lee and Teresa Rocciola: 

Laurie Lane 
Choral Manager 

I have emailed Jon the photo. 

Thanks! 
Again, I would do this but I'm concerned about format and I can't add photos.

**Comment by legion80** [comment]
I use this for now, but if she has a color photo that would be much better.

**Comment by Amalfi-Festival** [comment]
Yes, totally agree on the color photo! I think that headshot is 20 years old. But not as dated as Ursula's! 
She will work on it. 
Thanks!
