### ISSUE TITLE
ZH: link info regarding travel insurance

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#89]
Follow-up to #85 

@zhangshichao0322 which part of the following sentence should be turned into a link to the travel insurance section in the FAQ? Instead of making the whole sentence a link, I'd rather have "purchase travel insurance" be the text that's a link.

强烈建议您购买旅行保险，以确保在旅行取消或中断的情况下得到充分的保护。

**Comment by zhangshichao0322** [comment]
购买旅行保险
This is “purchase travel insurance “
