### ISSUE TITLE
Add Wei-Yi Yang to piano faculty / Session 2

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#92]
Wei-Yi Yang's bio and photo will be sent by email to Jon. 

Thank you!

**Comment by legion80** [comment]
Spun off a bug to @zhangshichao0322 for ZH translation

**Comment by Amalfi-Festival** [comment]
Thank you for taking care of this so quickly!
LH



Leslie Hyde
Executive Director
Amalfi Coast Music & Arts Festival
www.amalfi-festival.org
