### ISSUE TITLE
ZH translation for closing applications 

### ISSUE THREAD

**Issue by legion80** [Amalfi-Festival/amalfi-festival-org#95]
See commits related to #94. To test, I suggest mock-closing the piano program.

**Comment by zhangshichao0322** [comment]
Sorry, I'm not sure where to add it.  The chinese translation for "application closed" could be "报名已截止“

**Comment by legion80** [comment]
Look at `_includes/application-instructions-zh.md`

**Comment by legion80** [comment]
What needs to be translated is line 11 (Starting with "Note:"...)

**Comment by zhangshichao0322** [comment]
Done if this is the only one needs translation.

**Comment by legion80** [comment]
Done in 433f09c
