### ISSUE TITLE
PayPal Payment snag 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#96]
Now that we have started having people pay their balances (1st installment) for the Choral Program, we are running into a little snag that is probably impossible to avoid but I wanted to flag it for you. 

We've had 3 people this week who wanted to pay by credit card but NOT use their old PayPal accounts. However, once they go through the page you set up (https://amalfi-festival.org/payment?balance=1) and enter PayPal, as soon as they enter their email address (required), the PayPal system "recognizes" them and shifts them to their already established account. I tested this myself yesterday after someone complained and it happened to me too. I did discover that I could force myself out by logging out. But it's not obvious, especially if you are not a frequent PP user or generally not so tech savvy, like most of the choral folks. 

I just received another complaint now from someone saying this situation is not covered in the detailed instructions on the pay your balance  page. I guess it might be a good idea to include another step covering this point ???? 

Thanks!

**Comment by legion80** [comment]
I'll update the instructions. I didn't think that people would want to do that.
